name: artifacts_mmo_openapi
description: A starting point for Dart libraries or applications.
version: 2.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  openapi_generator_annotations: ^5.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  openapi_generator: ^5.0.2
  build_runner: ^2.0.0