//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

library openapi_generation;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:collection/collection.dart';
import 'package:http/http.dart';
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';

part 'api_client.dart';
part 'api_helper.dart';
part 'api_exception.dart';
part 'auth/authentication.dart';
part 'auth/api_key_auth.dart';
part 'auth/oauth.dart';
part 'auth/http_basic_auth.dart';
part 'auth/http_bearer_auth.dart';

part 'api/accounts_api.dart';
part 'api/achievements_api.dart';
part 'api/badges_api.dart';
part 'api/characters_api.dart';
part 'api/effects_api.dart';
part 'api/events_api.dart';
part 'api/grand_exchange_api.dart';
part 'api/items_api.dart';
part 'api/leaderboard_api.dart';
part 'api/maps_api.dart';
part 'api/monsters_api.dart';
part 'api/my_account_api.dart';
part 'api/my_characters_api.dart';
part 'api/npcs_api.dart';
part 'api/resources_api.dart';
part 'api/server_details_api.dart';
part 'api/simulation_api.dart';
part 'api/tasks_api.dart';
part 'api/token_api.dart';

part 'model/access_schema.dart';
part 'model/account_achievement_schema.dart';
part 'model/account_details.dart';
part 'model/account_details_schema.dart';
part 'model/account_leaderboard_schema.dart';
part 'model/account_leaderboard_type.dart';
part 'model/account_status.dart';
part 'model/achievement_response_schema.dart';
part 'model/achievement_rewards_schema.dart';
part 'model/achievement_schema.dart';
part 'model/achievement_type.dart';
part 'model/action_type.dart';
part 'model/active_character_schema.dart';
part 'model/active_event_response_schema.dart';
part 'model/active_event_schema.dart';
part 'model/add_account_schema.dart';
part 'model/add_character_schema.dart';
part 'model/badge_condition_schema.dart';
part 'model/badge_response_schema.dart';
part 'model/badge_schema.dart';
part 'model/bank_extension_schema.dart';
part 'model/bank_extension_transaction_response_schema.dart';
part 'model/bank_extension_transaction_schema.dart';
part 'model/bank_gold_transaction_response_schema.dart';
part 'model/bank_gold_transaction_schema.dart';
part 'model/bank_item_transaction_response_schema.dart';
part 'model/bank_item_transaction_schema.dart';
part 'model/bank_response_schema.dart';
part 'model/bank_schema.dart';
part 'model/change_password.dart';
part 'model/change_skin_character_data_schema.dart';
part 'model/change_skin_character_schema.dart';
part 'model/change_skin_response_schema.dart';
part 'model/character_fight_data_schema.dart';
part 'model/character_fight_response_schema.dart';
part 'model/character_fight_schema.dart';
part 'model/character_leaderboard_schema.dart';
part 'model/character_leaderboard_type.dart';
part 'model/character_movement_data_schema.dart';
part 'model/character_movement_response_schema.dart';
part 'model/character_multi_fight_result_schema.dart';
part 'model/character_response_schema.dart';
part 'model/character_rest_data_schema.dart';
part 'model/character_rest_response_schema.dart';
part 'model/character_schema.dart';
part 'model/character_skin.dart';
part 'model/character_transition_data_schema.dart';
part 'model/character_transition_response_schema.dart';
part 'model/characters_list_schema.dart';
part 'model/combat_result_schema.dart';
part 'model/combat_simulation_data_schema.dart';
part 'model/combat_simulation_request_schema.dart';
part 'model/combat_simulation_response_schema.dart';
part 'model/condition_operator.dart';
part 'model/condition_schema.dart';
part 'model/cooldown_schema.dart';
part 'model/craft_schema.dart';
part 'model/craft_skill.dart';
part 'model/crafting_schema.dart';
part 'model/data_page_account_achievement_schema.dart';
part 'model/data_page_account_leaderboard_schema.dart';
part 'model/data_page_achievement_schema.dart';
part 'model/data_page_active_character_schema.dart';
part 'model/data_page_active_event_schema.dart';
part 'model/data_page_badge_schema.dart';
part 'model/data_page_character_leaderboard_schema.dart';
part 'model/data_page_drop_rate_schema.dart';
part 'model/data_page_effect_schema.dart';
part 'model/data_page_event_schema.dart';
part 'model/data_page_ge_order_schema.dart';
part 'model/data_page_ge_order_history_schema.dart';
part 'model/data_page_item_schema.dart';
part 'model/data_page_log_schema.dart';
part 'model/data_page_map_schema.dart';
part 'model/data_page_monster_schema.dart';
part 'model/data_page_npc_item.dart';
part 'model/data_page_npc_schema.dart';
part 'model/data_page_resource_schema.dart';
part 'model/data_page_simple_item_schema.dart';
part 'model/data_page_task_full_schema.dart';
part 'model/delete_character_schema.dart';
part 'model/delete_item_response_schema.dart';
part 'model/delete_item_schema.dart';
part 'model/deposit_withdraw_gold_schema.dart';
part 'model/destination_schema.dart';
part 'model/drop_rate_schema.dart';
part 'model/drop_schema.dart';
part 'model/effect_response_schema.dart';
part 'model/effect_schema.dart';
part 'model/effect_subtype.dart';
part 'model/effect_type.dart';
part 'model/equip_request_schema.dart';
part 'model/equip_schema.dart';
part 'model/equipment_response_schema.dart';
part 'model/error_response_schema.dart';
part 'model/error_schema.dart';
part 'model/event_content_schema.dart';
part 'model/event_map_schema.dart';
part 'model/event_schema.dart';
part 'model/fake_character_schema.dart';
part 'model/fight_request_schema.dart';
part 'model/fight_result.dart';
part 'model/ge_buy_order_schema.dart';
part 'model/ge_cancel_order_schema.dart';
part 'model/ge_create_order_transaction_response_schema.dart';
part 'model/ge_order_created_schema.dart';
part 'model/ge_order_creationr_schema.dart';
part 'model/ge_order_response_schema.dart';
part 'model/ge_order_schema.dart';
part 'model/ge_order_transaction_schema.dart';
part 'model/ge_transaction_list_schema.dart';
part 'model/ge_transaction_response_schema.dart';
part 'model/ge_transaction_schema.dart';
part 'model/gathering_skill.dart';
part 'model/ge_order_history_schema.dart';
part 'model/give_gold_data_schema.dart';
part 'model/give_gold_response_schema.dart';
part 'model/give_gold_schema.dart';
part 'model/give_item_data_schema.dart';
part 'model/give_item_response_schema.dart';
part 'model/give_items_schema.dart';
part 'model/gold_schema.dart';
part 'model/http_validation_error.dart';
part 'model/interaction_schema.dart';
part 'model/inventory_slot.dart';
part 'model/item_response_schema.dart';
part 'model/item_schema.dart';
part 'model/item_slot.dart';
part 'model/item_type.dart';
part 'model/log_schema.dart';
part 'model/log_type.dart';
part 'model/map_access_type.dart';
part 'model/map_content_schema.dart';
part 'model/map_content_type.dart';
part 'model/map_layer.dart';
part 'model/map_response_schema.dart';
part 'model/map_schema.dart';
part 'model/monster_response_schema.dart';
part 'model/monster_schema.dart';
part 'model/monster_type.dart';
part 'model/my_account_details.dart';
part 'model/my_account_details_schema.dart';
part 'model/my_characters_list_schema.dart';
part 'model/npc_item.dart';
part 'model/npc_response_schema.dart';
part 'model/npc_schema.dart';
part 'model/npc_type.dart';
part 'model/npc_item_transaction_schema.dart';
part 'model/npc_merchant_buy_schema.dart';
part 'model/npc_merchant_transaction_response_schema.dart';
part 'model/npc_merchant_transaction_schema.dart';
part 'model/password_reset_confirm_schema.dart';
part 'model/password_reset_request_schema.dart';
part 'model/password_reset_response_schema.dart';
part 'model/rate_limit_schema.dart';
part 'model/recycling_data_schema.dart';
part 'model/recycling_items_schema.dart';
part 'model/recycling_response_schema.dart';
part 'model/recycling_schema.dart';
part 'model/resource_response_schema.dart';
part 'model/resource_schema.dart';
part 'model/response_schema.dart';
part 'model/reward_data_response_schema.dart';
part 'model/reward_data_schema.dart';
part 'model/reward_response_schema.dart';
part 'model/rewards_schema.dart';
part 'model/season_badge_schema.dart';
part 'model/season_schema.dart';
part 'model/season_skin_schema.dart';
part 'model/simple_effect_schema.dart';
part 'model/simple_item_schema.dart';
part 'model/skill.dart';
part 'model/skill_data_schema.dart';
part 'model/skill_info_schema.dart';
part 'model/skill_response_schema.dart';
part 'model/spawn_event_request.dart';
part 'model/status_response_schema.dart';
part 'model/status_schema.dart';
part 'model/storage_effect_schema.dart';
part 'model/task_cancelled_response_schema.dart';
part 'model/task_cancelled_schema.dart';
part 'model/task_data_schema.dart';
part 'model/task_full_response_schema.dart';
part 'model/task_full_schema.dart';
part 'model/task_response_schema.dart';
part 'model/task_schema.dart';
part 'model/task_trade_data_schema.dart';
part 'model/task_trade_response_schema.dart';
part 'model/task_trade_schema.dart';
part 'model/task_type.dart';
part 'model/token_response_schema.dart';
part 'model/transition_schema.dart';
part 'model/unequip_schema.dart';
part 'model/use_item_response_schema.dart';
part 'model/use_item_schema.dart';
part 'model/validation_error.dart';
part 'model/validation_error_loc_inner.dart';

/// An [ApiClient] instance that uses the default values obtained from
/// the OpenAPI specification file.
var defaultApiClient = ApiClient();

const _delimiters = {'csv': ',', 'ssv': ' ', 'tsv': '\t', 'pipes': '|'};
const _dateEpochMarker = 'epoch';
const _deepEquality = DeepCollectionEquality();
final _dateFormatter = DateFormat('yyyy-MM-dd');
final _regList = RegExp(r'^List<(.*)>$');
final _regSet = RegExp(r'^Set<(.*)>$');
final _regMap = RegExp(r'^Map<String,(.*)>$');

bool _isEpochMarker(String? pattern) =>
    pattern == _dateEpochMarker || pattern == '/$_dateEpochMarker/';
